### ISSUE TITLE
Spørsmål knyttet til etterlatte-samordning-vedtak

### ISSUE THREAD

**Issue by julieskjoy** [navikt/pensjon-etterlatte-saksbehandling#2228]
Hei! 

Jeg ser på API-spesifikasjonen til første endepunkt i tabellen til Applikasjonen "etterlatte-samordning-vedtak" at fødselsnummer skal angis i en fnr-header. Jeg lurer da på om det er nødvendig med tp-nummer i en egen header også? 
Spesielt med tanke på avsnittet "Autorisasjon", hvor det står "det må foreligge et tjenestepensjonsforhold i Tjenestepensjonsregisteret som gjelder kallende leverandør, personen vedtaket gjelder og på vedtakets virkningsdato".

**Comment by ingleivj** [comment]
Dette kommer snart, i #2261

**Comment by julieskjoy** [comment]
Skjønner, takk! Da lukker jeg dette issuet :)
